### ISSUE TITLE
🐛 [BUG] - ERC-20 Contract Addresses Clear on Edit

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#10]
### Description

When editing the name and ticker of an erc token I imported, I realized that when you click "edit" and then "save," the contract address of the token is removed, causing the balance to display "0." 

### Reproduction URL

https://github.com/maxbibeau

### Reproduction steps

```bash
1. Go to 'Home'
2. Click on 'Add Token'
3. Enter foobar token details
4. Click 'Save'
5. Click on the foobar token in home page
6. Click on the 'Edit' icon in the top right
7. (OPTIONAL) Make edits to name/ticker
8. Click 'Save'
9. View error
```

### Browsers

Chrome

### OS

Mac

**Comment by 0xalank** [comment]
https://github.com/PelagusWallet/pelagus-extension/commit/0220f6061ae2e3c338a3883bbf4d18ab34f3f011
