### ISSUE TITLE
🐛 [BUG] - sendTransaction API returns 200 regardless of success

### ISSUE THREAD

**Issue by Juuddi** [PelagusWallet/wallet-starter#11]
### Description

When submitting a transaction using the `quai_sendTransaction` method, regardless of whether the transaction fails or succeeds Pelagus returns a 200 code. The return also provides no data on what the transaction was, the hash of the transaction, or anything else.

The logs below are the return for both a successful and failed transaction.

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
Send a transaction via `quai_sendTransaction`
```

### Logs

```bash
Transaction sent: { "code":200 }
```

### Browsers

Chrome

### OS

Mac

**Comment by 0xalank** [comment]
https://github.com/PelagusWallet/pelagus-extension/commit/7be77945b51ae840816a31885937378441087b2e
