### ISSUE TITLE
🐛 [BUG] - Copy Mining Config returns undefined

### ISSUE THREAD

**Issue by Juuddi** [PelagusWallet/wallet-starter#13]
### Description

When clicking the "Copy Mining Config" button in general settings, all of the outputs return undefined.

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
Go to settings -> general -> copy mining config -> paste output somewhere
```

### Logs

```bash
ZONE_0_0_COINBASE=undefined
ZONE_0_1_COINBASE=undefined
ZONE_0_2_COINBASE=undefined
ZONE_1_0_COINBASE=undefined
ZONE_1_1_COINBASE=undefined
ZONE_1_2_COINBASE=undefined
ZONE_2_0_COINBASE=undefined
ZONE_2_1_COINBASE=undefined
ZONE_2_2_COINBASE=undefined
```

**Comment by 0xalank** [comment]
https://github.com/PelagusWallet/pelagus-extension/commit/6d111fb63ca72c1f27a2c44c90371f5233d5a36e
