### ISSUE TITLE
🐛 [BUG] - Incorrect copy and broken link on "Send" screen

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#15]
### Description

The copy on the "Send" page is "Select from Wallet 1," which does not make sense given Pelagus' current structure. The "Learn More" link out on that same page also does not work. 
<img width="367" alt="PelagusWalletCopy" src="https://github.com/PelagusWallet/pelagus-extension/assets/101674286/4bf13355-94a1-4f5a-af34-549c1fa01ffc">

### Reproduction URL

https://github.com/maxbibeau

### Reproduction steps

```bash
1. Go to 'Home'
2. Click on 'Send'
3. See error
```

### Screenshots

```bash
This is set incorrectly, unable to insert screenshots here
```

### Browsers

Chrome

### OS

Mac

**Comment by 0xalank** [comment]
Unsure what  you mean by "incorrect copy" and learn more is pending docs.

**Comment by 0xmgb** [comment]
> Unsure what you mean by "incorrect copy" and learn more is pending docs.

I'm referring to the "Select from Wallet 1." Given Pelagus creates 9 accounts for each new user and doesn't currently support creating/deleting accounts, there is no Wallet 2. I'd suggest "Select Account to Send From" as a more accurate description.

**Comment by 0xalank** [comment]
Not relevant anymore with single address change
