### ISSUE TITLE
🐛 [BUG] - Unable to select contact during "Send" flow

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#16]
### Description

After creating a contact, users are unable to select them as the recipient of their transaction. As part of the "Send" flow, users are prompted to either paste a recipient address or select a contact; selecting a contact does not work.

### Reproduction URL

https://github.com/maxbibeau

### Reproduction steps

```bash
1. Go to 'Home'
2. Click on 'Contacts' Page
3. Create a new contact
4. Return to 'Home'
5. Click on 'Send'
6. Select any account to send from
7. View error
```

### Browsers

Chrome

### OS

Mac

**Comment by 0xalank** [comment]
https://github.com/PelagusWallet/pelagus-extension/commit/745d86e8e8c44fc75c6d5d7a674658b9fd5edd9c
