### ISSUE TITLE
🐛 [BUG] - Editing contact clears address state

### ISSUE THREAD

**Issue by Juuddi** [PelagusWallet/wallet-starter#17]
### Description

After creating a contact, going back to edit the contact address and click save clears the contact address and prevents you from adding any more addresses.

Changing the contact name and clicking save works correctly, but the address gets cleared on every edit. Adding a new address to the contact on the edit page always clears the address and yields a `0 Total Addresses` in the contact page.

### Reproduction URL

https://github.com/Juuddi

### Reproduction steps

```bash
1. Go to the contacts page
2. Create a contact with a random address and name
3. Save the contact and exit
4. Return to the contacts page and click edit
5. Either click save immediately or replace the existing address with a new one and click save
6. Return to the main contacts page and see the `0 Total Addresses` under the edited contact
```

**Comment by 0xalank** [comment]
https://github.com/PelagusWallet/pelagus-extension/commit/5039b3e561cd535a7b25a6cfe001685e739e51f7
