### ISSUE TITLE
🐛 [BUG] - Total fee UX issue in dark mode

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#18]
### Description

When the application is in Dark Mode, the "Total Fee" bar in the "Send" flow is whited out and unviewable. 
<img width="363" alt="TotalFee" src="https://github.com/PelagusWallet/pelagus-extension/assets/101674286/0097e04d-83c1-4beb-b411-f74ea04bffc4">

### Reproduction URL

https://github.com/maxbibeau

### Reproduction steps

```bash
1. Go to 'Settings'
2. Click on 'General'
3. Click on 'Toggle Dark Mode' (if you are not already in dark mode)
4. Go to 'Home'
5. Click on 'Send'
6. Click 'Select' on any account
7. Paste an account or select a contact
8. View error
```

### Browsers

Chrome

### OS

Mac

**Comment by 0xalank** [comment]
https://github.com/PelagusWallet/pelagus-extension/commit/431bb57327215f08864b9a639b2f8a4122a18fa8
