### ISSUE TITLE
🐛 [BUG] - Minor copy issue on import wallet flow

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#19]
### Description

After importing a wallet, the password prompt copy is "Enter a password to generate a secure phrase." This copy is incorrect, given the user already has their secure phrase and will not be generating a new one. 
![Screen Shot 2023-06-14 at 12 09 28 PM](https://github.com/PelagusWallet/pelagus-extension/assets/101674286/5e302cf4-a4a3-49d1-b13c-639ec09e7783)

### Reproduction URL

https://github.com/maxbibeau

### Reproduction steps

```bash
1. Download Pelagus
2. Click on 'Import Existing Wallet'
3. Enter secure phrase
4. Continue to password creation screen
5. View error
```

### Browsers

Chrome

### OS

Mac

**Comment by 0xalank** [comment]
https://github.com/PelagusWallet/pelagus-extension/commit/5bf430e27afbaf99c5b20fec1acd057592b373f6
