### ISSUE TITLE
💡 [REQUEST] - Remove redundant "accounts" page and improve 'receive' page

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#22]
### Summary

Currently the "receive" page is identical to the "accounts" page. I propose we remove the pixelated icon in the top right of the wallet that leads to the "accounts" page and just replace it with the "receive" button. The option to display QR codes from the receive button would also be a big plus.

### Basic Example

Example: Remove top-right pixelated icon, the only way to access accounts is the receive page. Add a "QR" icon to each account on the receive page.

### Drawbacks

If we ever add a create/delete account feature, we would need a place for those options to live. An accounts page would likely make the most sense for this. I think the most important short-term item is for the receive page to be differentiated from the accounts page, either through QR codes or some other means.

**Comment by 0xalank** [comment]
Yep, valid request. Plan is to make the receive a QR code.

**Comment by 0xalank** [comment]
https://github.com/PelagusWallet/pelagus-extension/commit/adabc2c9bc9cd753cc5d54dc05d2d58441aa5371

**Comment by 0xalank** [comment]
![Screenshot 2023-06-26 at 10 48 16 AM](https://github.com/PelagusWallet/pelagus-extension/assets/14866363/09da16ee-f920-489a-bb67-759dc79fbdd6)
