### ISSUE TITLE
🐛 [BUG] - Private key export page has confusing UI

### ISSUE THREAD

**Issue by Juuddi** [PelagusWallet/wallet-starter#24]
### Description

<img width="372" alt="Screenshot 2023-06-16 at 11 47 22 AM" src="https://github.com/PelagusWallet/pelagus-extension/assets/98721462/558f7e2a-d00f-4d4d-bfac-e1b96ab6ea1a">

When going to export your private key, this page pops up. The UI doesn't follow any existing standard within the app - just needs to be cleaned up to match rest of extension. Also the back button is unclickable while the modal is up, which was a bit confusing when first using the feature. Consider hiding it to prevent confusion or not using a modal popup.

### Reproduction URL

https://github.com/Juuddi

### Reproduction steps

```bash
1. Go to settings
2. Click on Security and Privacy
3. Click export private key
4. Enter password and click reveal
```

### Browsers

Chrome

### OS

Mac

**Comment by 0xalank** [comment]
Fixed https://github.com/PelagusWallet/pelagus-extension/commit/435f8365316392512d1339bf25e7da5ac89288f3
