### ISSUE TITLE
🐛 [BUG] - Placeholder zeroes don't clear when entering a send amount in sending flow

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#25]
### Description

When going through the send flow to send a transaction, the default "0.0" amount to send does not clear when a user begins inputting their own value. If the user clicks the middle of the "amount" option and enters a 1, they will end up sending "0.10" Quai instead of the intended "1" Quai. Creates additional friction/button presses. 

### Reproduction URL

https://github.com/maxbibeau

### Reproduction steps

```bash
1. Go to 'Home'
2. Click on 'Send'
3. Select account to send from
4. Input recipient address
5. Click on the default "0.0" amount to send
6. Enter '1'
7. View error
```

**Comment by 0xalank** [comment]
fixed https://github.com/PelagusWallet/pelagus-extension/commit/e6ae624f4729053c2597f9e9b54a2fb7ee345b82
