### ISSUE TITLE
🐛 [BUG] - Blue line stays under 'activity' page while user is on 'assets' tab

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#27]
### Description

When a user clicks on the activity page then goes to a different tab of the wallet, then returns to the home screen, the blue line stays under "activity" while the screen is actually on "assets." The user also can't fix the blue line by clicking "assets" and must click "activity" then go back to "assets" to fix the blue line. 

### Reproduction URL

https://github.com/maxbibeau

### Reproduction steps

```bash
1. Go to 'Home'
2. Click on 'Activity'
3. Click on 'NFTs' tab on the bottom
4. Click 'Home' tab on the bottom
4. View error
```

### Browsers

Chrome

### OS

Mac

**Comment by 0xalank** [comment]
fixed https://github.com/PelagusWallet/pelagus-extension/commit/a590c379c5c9828db050e100f738e3a114f259da
