### ISSUE TITLE
💡 [REQUEST] - Add motion to activity tab

### ISSUE THREAD

**Issue by 0xmgb** [PelagusWallet/wallet-starter#28]
### Summary

Red indicators for a failed transaction and blue indicators for successful are a nice touch. However, the wallet should differentiate more between a "sending" (pending) transaction and a "sent" (confirmed) transaction. At a quick glance, both icons look very similar and could be easily confused. 

Additionally, having a spinner while the transaction is pending demonstrates that the transaction is "in motion" or on the way to its destination, while the current static arrow seems to indicate the transaction has already been sent to the recipient (completed). I have not tested it, but I imagine similar changes could be made to the receiving/received icons. 

### Basic Example

Replace "sending" and "receiving" icon with a spinner to differentiate between in-progress transactions and completed transactions.

### Drawbacks

Potentially something on the backend I'm unaware of.

**Comment by 0xalank** [comment]
This was a request from @kiltsonfire and core team as we'd like them to seem the same.

**Comment by 0xmgb** [comment]
> This was a request from @kiltsonfire and core team as we'd like them to seem the same.

What was the reasoning behind this request? I believe there should be more discussion around this UX for the following reasons:

1. When the "sending" and "sent" icons are intended to seem the same, users may find it difficult to determine whether a transaction has been successfully completed or is still pending. This lack of clarity can create confusion and make it challenging to track the progress of transactions.
2. Ambiguous icons can lead to user error, where individuals mistakenly believe that a transaction is completed and funds have been sent when, in reality, the transaction is still in progress or has encountered an error. This can result in users sending funds multiple times or believing that a transaction was successful when it wasn't.
3. Metamask and other popular software wallets have very sharp color distinction to help users differentiate between "pending," "confirmed," and "failed" transactions. Pending is made very clear with yellow text and icons, and confirmed is defined by green icons and text.

EDIT: Particularly on the receiving end, the "pending receipt" and "received" icons need to be significantly different or scams that function much like bounced checks can abuse users.

**Comment by 0xmgb** [comment]
After discussing with @djadih, the core recommendation seems to be that motion should not be used so users don't think they have to leave Pelagus open while a transaction is sending -- however, it was agreed upon that it is important for users to be able to differentiate between "sending/broadcasted" and "sent." More discussion on how to resolve this is needed.
