### ISSUE TITLE
🐛 [BUG] - Faucet link doesn't route to the faucet page

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#30]
### Description
This issue was found on 51e4361 commit hash
- Faucet link doesn't route to the Faucet Page

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
1. Click on Pelagus extension
2. Click on the Faucet icon on the main page
```

### Browsers

Chrome

### OS

Linux

**Comment by 0xalank** [comment]
Faucet routes properly when I tried. Can you reproduce?

**Comment by 0xalank** [comment]
Faucet link needs to be in `.env` as `PLASMO_PUBLIC_FAUCET_LINK=https://dashboard.sandbox.quai.network/faucet`
