### ISSUE TITLE
🐛 [BUG] - Can replace existing account without logging out

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#31]
### Description
This issue was found on 51e4361 commit hash
 After the account creation if you click back if goes to the create password page, and its possible to create a new account and it will replace the existing account in the wallet. I think creating new account should happen after you logout of the wallet. Any flow to create a new account should come after. 

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
1. Go to Pelagus wallet extension
2. Create an account
3. After successful creation click on the back button of the browser
4. You can create new account that can replace the existing wallet
```

### Browsers

Chrome

### OS

Linux

**Comment by 0xalank** [comment]
Need more discovery on this. Basically just saying we shouldn't be able to go back during setup?

**Comment by gameofpointers** [comment]
@alanorwick after the setup too, if there is a wallet state we should not be able to just replace the wallet. Only after the logout sequence is completed it should be possible

**Comment by 0xalank** [comment]
fixed: https://github.com/PelagusWallet/pelagus-extension/commit/f58b384a9b58c25ecc8c371c1220befed033cea2
