### ISSUE TITLE
🐛 [BUG] - NO back button in the receive page (`<`)

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#32]
### Description
This issue was found on 51e4361 commit hash
NO back button in the receive page (`<`)

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
1. Go to Pelagus extension
2. Click on the receive button
```

### Browsers

Chrome

### OS

Linux

**Comment by 0xalank** [comment]
Fixed https://github.com/PelagusWallet/pelagus-extension/commit/165fa24fdf6e53051d25786d1eb3415023f69bb5
