### ISSUE TITLE
🐛 [BUG] - Random send page exists in the Add token page

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#33]
### Description
This issue was found on 51e4361 commit hash
If you click on `Add Token` on the main page and click on the back button at the top, it goes to the `send` and `swap` page. Two things here, we should not go back to the send page and I thought the swap feature was removed.

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
1. Go to Pelagus extension
2. Click on the Add Token Button
3. Click on the back button
```

### Browsers

Chrome

### OS

Linux

**Comment by 0xalank** [comment]
Closed https://github.com/PelagusWallet/pelagus-extension/commit/29c62413b6683cd13d068b2345f1e379ff1e15b1
