### ISSUE TITLE
🐛 [BUG] - Background is Dark on the Light mode on the test input box

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#34]
## Starting Page
![2023-06-28-100947_864x534_scrot](https://github.com/PelagusWallet/pelagus-extension/assets/110414931/2968e462-677c-45fd-86c2-348bd4c6cd44) 

## Add account page
![2023-06-28-103118_351x269_scrot](https://github.com/PelagusWallet/pelagus-extension/assets/110414931/7c574e1d-bcff-4be2-914a-cf4d0f675cb9)

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
1. Go to Extension
2. Click on top right icon
3. Click on Add account
4. See error
```

### Browsers

Chrome

### OS

Linux

**Comment by 0xalank** [comment]
fixed: https://github.com/PelagusWallet/pelagus-extension/commit/f58b384a9b58c25ecc8c371c1220befed033cea2
