### ISSUE TITLE
💡 [REQUEST] - More info on the Address

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#36]
### Summary

![2023-06-28-103559_358x237_scrot](https://github.com/PelagusWallet/pelagus-extension/assets/110414931/aa4f7b50-b9b0-44c8-9fa7-c8079ff4dfe1)

Just having the address name feels weird, I think the location should also go with it

### Basic Example

- Want to see more metadata about the account especially the location to which it belongs to
- Also be able to copy it from the dropdown

### Drawbacks

If added too much data it can look confusing, so has to be careful with the metadata being added

**Comment by 0xalank** [comment]
fixed https://github.com/PelagusWallet/pelagus-extension/commit/e91dda1981f805025591f30c65bc777200c29435
