### ISSUE TITLE
🐛 [BUG] - Back button doesnt work after first time on the Add Token page

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#38]
### Description

Back button doesnt work after first time on the Add Token page

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
1. Go to extension
2. Click on Add Token
3. Click on Back button
4. Click on Add Token again
5. Click on Back Button, it doesn't go back
```

### Browsers

Chrome

### OS

Linux

**Comment by 0xalank** [comment]
fixed https://github.com/PelagusWallet/pelagus-extension/commit/82a5e6ccf9761948b31cdc7b93309aa8892a8e2a
