### ISSUE TITLE
🐛 [BUG] - Back button on the Switch network on Main page goes to Setting Page

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#39]
### Description

 Back button on the Switch network on Main page goes to Setting Page

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
1. Go to Wallet extension
2. Click on Colosseum Dropdown (Switch Network)
3. Click on Back button
4. See error
```

### Browsers

Chrome

### OS

Linux

**Comment by 0xalank** [comment]
fixed https://github.com/PelagusWallet/pelagus-extension/commit/9c6523bb1ce8109c93eb9718c09ba9af758e6011
