### ISSUE TITLE
can you prevention of dust token and scam token entering the pelagus wallet in the future pelagus team thank you.

### ISSUE THREAD

**Issue by Blincke07** [PelagusWallet/wallet-starter#4]
### Start Date

06/13/2023

### Summary

prevention of dust token and scam token entering the pelagus wallet in the future

### Basic Example

prevention of dust token and scam token entering the pelagus wallet in the future

### Drawbacks

prevention of dust token and scam token entering the pelagus wallet in the future

**Comment by 0xalank** [comment]
Sure, right now tokens are auto add. So you can manually add / delete the tokens in your wallet. This may change with more advanced lookups. We could also add a filter on tokens to show at X amount.

Closing as this is scoped as future work and not relevant at the moment.
