### ISSUE TITLE
🐛 [BUG] - Modal Popup on the incorect password to reveal password should be themed

### ISSUE THREAD

**Issue by gameofpointers** [PelagusWallet/wallet-starter#40]
### Description

Modal Popup on the incorect password to reveal password should be themed, similar to the popup that already exists for success
![2023-06-29-100457_759x341_scrot](https://github.com/PelagusWallet/pelagus-extension/assets/110414931/0b6a1e04-cd3a-4f0e-b82d-ae8afdf084d8)

### Reproduction URL

https://github.com/PelagusWallet/pelagus-extension

### Reproduction steps

```bash
1. Go to Pelagus extension
2. Click on Click on an account
3. Click on Reveal Secret Phrase
4. Type in Wrong Password
5. See the Modal
```

### Browsers

Chrome

### OS

Linux

**Comment by 0xalank** [comment]
fixed https://github.com/PelagusWallet/pelagus-extension/commit/2c8e0728d5b128a82a65aa1dd577974212d6a03e
