### ISSUE TITLE
🐛 [BUG] - seed phrase display should not have hover effects

### ISSUE THREAD

**Issue by wizeguyy** [PelagusWallet/wallet-starter#42]
### Description

When you hover over words in the seed list, the bubble goes black and hard to read. There should be no hover effect.

![IMG_5865](https://github.com/PelagusWallet/pelagus-extension/assets/102399132/27a0157e-5360-48c9-87b1-ab54b6d5e777)

### Reproduction URL

letsremovethisfromthetemplate.com

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Comment by 0xalank** [comment]
fixed https://github.com/PelagusWallet/pelagus-extension/commit/4f82a64211926a947a1788bc598bcaa8bc20a49b
